def algoritmos():
	print(" ===========================================================================")
	print("|            ALGORITMOS CRIPTOGRAFICOS                                      |")
	print("|        SINTAXIS: python3 main.py <algoritmo>                              |")
	print("| <Algoritmo>:                                                              |")
	print("|              -em Esterilizacion de un medio                               |")
	print("|              -oi Obtener imagen de un pendrive                            |")
	print("|              -mi montar imagen                                            |")
	print("|              -at Algoritmo Atbash                                         |")
	print(" ===========================================================================")
	print("Consultar la ayuda de un algoritmo:")
	print("                         	SINTAXIS:")
	print("                                      python3 main.py <algoritmo>")
def ayudasterilizar():
	print("================================================MENU=================================================")
	print("| Sintaxis:                                                                                          |")
	print("| python main.py -of Dispositivo -bs tamañoBloque -n Nombre -v Iteraciones                           |")
	print("|                                                                                                    |")
	print("| Dispositivo: Dirección donde esta montada el Dispositivo, df -h para obtenerla                     |")
	print("| tamañoBloque: tamaño de los bloques, fdisk -l 'ruta' para obtenerlo o 512 por defecto              |")
	print("| Nombre: nombre que se le asignara al Dispositivo despues de formatear                              |")
	print("| Iteraciones: Numero de iteraciones para rellenar con ceros y numeros aleatorios el Dispositivo     |")
	print("|====================================================================================================|")
	print("| Ejemplo:                                                                                           |")
	print("| python main.py -of /dev/sdb1 -bs 512 -n Mi-USB -v 99                                               |")	
	print("|====================================================================================================|")
	print("| Creado por: Davinson Mellizo                                                                       |")
	print("| Correo: davinsonmellizo@unicauca.edu.co                                                            |")
	print("| Profesor: Siler Amador Donado                                                                      |")
	print("| Fecha: 21/05/2019                                                                                  |")
	print("| Repositorio: https://github.com/davinsonMellizo/Esterilizacion.git                                 |")
	print("=====================================================================================================")

		